### ISSUE TITLE
swig runtime build errors: ringtones/datetimepicker extensions

### ISSUE THREAD

**Issue by jtara** [rhomobile/rhodes#872]
Current master as of 2017-05-25 a5b40d4
Cannot build for iOS simulator. Have not tried others.

As workaround, I wonder if there is easy way to skip swig on extensions I won't use? (Of course, can just remove the extension!)

Typical error message in build:

❌  /Users/jon/.rvm/gems/ruby-2.3.4@rhodes_master_6.0_a52b40d4/gems/rhodes-6.0.0/platform/shared/ruby/ext/ringtones/ringtones_wrap.c:1565:11: '__builtin_choose_expr' requires a constant expression

    obj = Data_Wrap_Struct(klass, 0, 0, ptr);

**Comment by alex-epifanoff** [comment]
Probably this is fixed in 6.0, but I'm not sure how stable RhoSim/Mac is currently.

**Comment by jtara** [comment]
I just checked current master ed93622fc5708d63c19998da7773950e65171ceb, it is not fixed.

This is for iOS simulator, not RhoSim.

**Comment by alex-epifanoff** [comment]
have not observed it in 6.0 release
